parameters:
    fsc_hateoas.serializer.link_serialization_helper.class: FSC\HateoasBundle\Serializer\LinkSerializationHelper
    fsc_hateoas.factory.link.class: FSC\HateoasBundle\Factory\LinkFactory
    fsc_hateoas.factory.parameters.class: FSC\HateoasBundle\Factory\ParametersFactory
    fsc_hateoas.factory.content.class: FSC\HateoasBundle\Factory\ContentFactory
    fsc_hateoas.factory.form_view.class: FSC\HateoasBundle\Factory\FormViewFactory
    fsc_hateoas.serializer.xml_form_view.class: FSC\HateoasBundle\Serializer\XmlFormViewSerializer
    fsc_hateoas.serializer.event_subscriber.link.class: FSC\HateoasBundle\Serializer\EventSubscriber\LinkEventSubscriber
    fsc_hateoas.serializer.event_subscriber.embedder.class: FSC\HateoasBundle\Serializer\EventSubscriber\EmbedderEventSubscriber
    fsc_hateoas.serializer.handler.pagerfanta.class: FSC\HateoasBundle\Serializer\Handler\PagerfantaHandler
    fsc_hateoas.serializer.handler.halpagerfanta.class: FSC\HateoasBundle\Serializer\Handler\HalPagerfantaHandler
    fsc_hateoas.serializer.handler.form_view.class: FSC\HateoasBundle\Serializer\Handler\FormViewHandler
    fsc_hateoas.serializer.handler.form.class: FSC\HateoasBundle\Serializer\Handler\FormHandler
    fsc_hateoas.factory.identity.class: FSC\HateoasBundle\Factory\IdentityFactory
    fsc_hateoas.routing.generator.class: FSC\HateoasBundle\Routing\UrlGenerator

    fsc_hateoas.json.links_key: ~
    fsc_hateoas.json.relations_key: ~

services:
    fsc_hateoas.serializer.link_serialization_helper:
        class: %fsc_hateoas.serializer.link_serialization_helper.class%
        public: false

    fsc_hateoas.factory.link:
        class: %fsc_hateoas.factory.link.class%
        public: false
        arguments:
            - @fsc_hateoas.routing.generator
            - @fsc_hateoas.metadata.factory
            - @fsc_hateoas.factory.parameters

    fsc_hateoas.factory.parameters:
        class: %fsc_hateoas.factory.parameters.class%
        public: false

    fsc_hateoas.factory.content:
        class: %fsc_hateoas.factory.content.class%
        public: false
        arguments:
            - @fsc_hateoas.metadata.factory
            - @fsc_hateoas.factory.parameters
            - @service_container

    fsc_hateoas.factory.form_view:
        class: %fsc_hateoas.factory.form_view.class%
        arguments:
            - @fsc_hateoas.routing.generator
            - @form.factory

    fsc_hateoas.serializer.xml_form_view:
        class: %fsc_hateoas.serializer.xml_form_view.class%

    fsc_hateoas.serializer.event_subscriber.link:
        class: %fsc_hateoas.serializer.event_subscriber.link.class%
        arguments:
            - @fsc_hateoas.factory.link
            - @fsc_hateoas.serializer.link_serialization_helper
            - %fsc_hateoas.json.links_key%
        tags:
            - { name: jms_serializer.event_subscriber }

    fsc_hateoas.serializer.event_subscriber.embedder:
        class: %fsc_hateoas.serializer.event_subscriber.embedder.class%
        arguments:
            - @fsc_hateoas.factory.content
            - @jms_serializer.metadata_factory
            - @fsc_hateoas.metadata.relations_manager
            - @fsc_hateoas.factory.parameters
            - null
            - %fsc_hateoas.json.relations_key%
        tags:
            - { name: jms_serializer.event_subscriber }

    fsc_hateoas.serializer.handler.pagerfanta:
        class: %fsc_hateoas.serializer.handler.pagerfanta.class%
        arguments:
            - @jms_serializer.metadata_factory
            - @fsc_hateoas.serializer.event_subscriber.embedder
            - @fsc_hateoas.serializer.event_subscriber.link
            - true
            - %fsc_hateoas.json.links_key%
            - %fsc_hateoas.json.relations_key%
        tags:
            - { name: jms_serializer.subscribing_handler }

    fsc_hateoas.serializer.handler.halpagerfanta:
        class: %fsc_hateoas.serializer.handler.halpagerfanta.class%
        parent: fsc_hateoas.serializer.handler.pagerfanta
        tags:
            - { name: jms_serializer.subscribing_handler }

    fsc_hateoas.serializer.handler.form_view:
        class: %fsc_hateoas.serializer.handler.form_view.class%
        arguments:
            - @fsc_hateoas.serializer.xml_form_view
            - @fsc_hateoas.serializer.event_subscriber.embedder
            - @fsc_hateoas.serializer.event_subscriber.link
        tags:
            - { name: jms_serializer.subscribing_handler }

    fsc_hateoas.serializer.handler.form:
        class: %fsc_hateoas.serializer.handler.form.class%
        tags:
            # Added by DI extension
            #- { name: jms_serializer.subscribing_handler }

    fsc_hateoas.factory.identity:
        class: %fsc_hateoas.factory.identity.class%

    fsc_hateoas.routing.generator:
        class: %fsc_hateoas.routing.generator.class%
        arguments:
            - @router
