parameters:
    fsc_hateoas.serializer.link_serialization_helper.class: FSC\HateoasBundle\Serializer\LinkSerializationHelper
    fsc_hateoas.factory.link.class: FSC\HateoasBundle\Factory\LinkFactory
    fsc_hateoas.factory.parameters.class: FSC\HateoasBundle\Factory\ParametersFactory
    fsc_hateoas.factory.content.class: FSC\HateoasBundle\Factory\ContentFactory
    fsc_hateoas.factory.links_aware_wrapper.class: FSC\HateoasBundle\Factory\LinksAwareWrapperFactory
    fsc_hateoas.factory.route_aware_form_view.class: FSC\HateoasBundle\Factory\RouteAwareFormViewFactory
    fsc_hateoas.resolver.arguments.class: FSC\HateoasBundle\Resolver\ArgumentsResolver
    fsc_hateoas.serializer.xml_form_view.class: FSC\HateoasBundle\Serializer\XmlFormViewSerializer
    fsc_hateoas.serializer.event_subscriber.link.class: FSC\HateoasBundle\Serializer\EventSubscriber\LinkEventSubscriber
    fsc_hateoas.serializer.event_subscriber.embedder.class: FSC\HateoasBundle\Serializer\EventSubscriber\EmbedderEventSubscriber
    fsc_hateoas.serializer.handler.pagerfanta.class: FSC\HateoasBundle\Serializer\Handler\PagerfantaHandler
    fsc_hateoas.serializer.handler.route_aware_form_view.class: FSC\HateoasBundle\Serializer\Handler\RouteAwareFormViewHandler
    fsc_hateoas.serializer.handler.links_aware_wrapper.class: FSC\HateoasBundle\Serializer\Handler\LinksAwareWrapperHandler
    fsc_hateoas.serializer.handler.form_view.class: FSC\HateoasBundle\Serializer\Handler\FormViewHandler
    fsc_hateoas.serializer.handler.form.class: FSC\HateoasBundle\Serializer\Handler\FormHandler

services:
    fsc_hateoas.serializer.link_serialization_helper:
        class: %fsc_hateoas.serializer.link_serialization_helper.class%
        public: false

    fsc_hateoas.factory.link:
        class: %fsc_hateoas.factory.link.class%
        public: false
        arguments:
            - @router
            - @fsc_hateoas.metadata.factory
            - @fsc_hateoas.factory.parameters

    fsc_hateoas.factory.parameters:
        class: %fsc_hateoas.factory.parameters.class%
        public: false

    fsc_hateoas.factory.content:
        class: %fsc_hateoas.factory.content.class%
        public: false
        arguments:
            - @fsc_hateoas.metadata.factory
            - @fsc_hateoas.factory.parameters
            - @fsc_hateoas.resolver.arguments
            - @service_container

    fsc_hateoas.factory.links_aware_wrapper:
        class: %fsc_hateoas.factory.links_aware_wrapper.class%
        arguments:
            - @router
            - @fsc_hateoas.metadata.factory
            - @service_container

    fsc_hateoas.factory.route_aware_form_view:
        class: %fsc_hateoas.factory.route_aware_form_view.class%
        arguments:
            - @form.factory

    fsc_hateoas.resolver.arguments:
        class: %fsc_hateoas.resolver.arguments.class%
        public: false

    fsc_hateoas.serializer.xml_form_view:
        class: %fsc_hateoas.serializer.xml_form_view.class%

    fsc_hateoas.serializer.event_subscriber.link:
        class: %fsc_hateoas.serializer.event_subscriber.link.class%
        arguments:
            - @fsc_hateoas.factory.link
            - @fsc_hateoas.serializer.link_serialization_helper
        tags:
            - { name: jms_serializer.event_subscriber }

    fsc_hateoas.serializer.event_subscriber.embedder:
        class: %fsc_hateoas.serializer.event_subscriber.embedder.class%
        arguments:
            - @fsc_hateoas.factory.content
            - @jms_serializer.metadata_factory
            - @fsc_hateoas.factory.links_aware_wrapper
            - @fsc_hateoas.factory.parameters
        tags:
            - { name: jms_serializer.event_subscriber }

    fsc_hateoas.serializer.handler.pagerfanta:
        class: %fsc_hateoas.serializer.handler.pagerfanta.class%
        arguments:
            - @jms_serializer.metadata_factory
            - true
        tags:
            - { name: jms_serializer.subscribing_handler }

    fsc_hateoas.serializer.handler.route_aware_form_view:
        class: %fsc_hateoas.serializer.handler.route_aware_form_view.class%
        arguments:
            - @router
        tags:
            - { name: jms_serializer.subscribing_handler }

    fsc_hateoas.serializer.handler.links_aware_wrapper:
        class: %fsc_hateoas.serializer.handler.links_aware_wrapper.class%
        arguments:
            - @fsc_hateoas.serializer.link_serialization_helper
        tags:
            - { name: jms_serializer.subscribing_handler }

    fsc_hateoas.serializer.handler.form_view:
        class: %fsc_hateoas.serializer.handler.form_view.class%
        arguments:
            - @fsc_hateoas.serializer.xml_form_view
        tags:
            - { name: jms_serializer.subscribing_handler }

    fsc_hateoas.serializer.handler.form:
        class: %fsc_hateoas.serializer.handler.form.class%
        tags:
            - { name: jms_serializer.subscribing_handler }
